version: "3.3"
services:
  api-gateway:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./config/.env
    networks:
      default:
        ipv4_address: 10.0.0.21
    expose:
      - "8081"
    ports:
      - "8081:8081" 
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
        