service:
  name: "app"
  port: "8083"
  env: "stag"
  allow_origins: "http://localhost:3000"

mongodb:
  database: "food-delivery"
  database_uri: "mongodb+srv://kartikshankh:VlykdctHu1GIv1u9@cluster0.loao0fq.mongodb.net/"
  geo:
    distance:
      rider: "20000"
  collection:
    rider: "rider"
    user: "user"
    restaurant: "restaurant"
    orders: "orders"

jwt_secret: "jwt_secret343r1234fdsac"